defmodule EcritsWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :ecrits

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_ecrits_key",
    signing_salt: "pTMmQs5a",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Cross-origin isolation for the office WASM editor (COOP/COEP). Must run
  # before Plug.Static so the `/assets/office/*` artifacts are served with the
  # isolation headers too. Scoped to the workspace page + office assets only.
  plug EcritsWeb.Plugs.CrossOriginIsolationPlug

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :ecrits,
    gzip: not code_reloading?,
    only: EcritsWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  if Mix.env() == :dev do
    plug Tidewave
  end

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # The `doc.*` MCP server (consumed by ACP agents over streamable HTTP) must run
  # before Plug.Parsers so it can read the raw JSON-RPC body itself.
  plug EcritsWeb.Plugs.DocToolsMCPPlug

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug EcritsWeb.Router
end
