defmodule ContractWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :contract

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_contract_key",
    signing_salt: "pTMmQs5a",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :contract,
    gzip: not code_reloading?,
    only: ContractWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  if Mix.env() == :dev do
    plug Tidewave
  end

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :contract
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  # Test-only sandbox endpoint. Wallaby's browser session hits `/sandbox`
  # with a user-agent header carrying SQL sandbox metadata so it shares the
  # same Ecto checkout as the test process. `compile_env` ensures this plug
  # is fully elided from prod / dev builds.
  if Application.compile_env(:contract, :sql_sandbox) do
    plug Phoenix.Ecto.SQL.Sandbox,
      at: "/sandbox",
      header: "user-agent",
      repo: Contract.Repo
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # For /mcp the inbound MCP plug needs the raw JSON-RPC body (so it can
  # respond with a JSON-RPC -32700 parse error instead of a generic 400).
  # We stash the raw body in assigns and zero out body_params so
  # Plug.Parsers below is a no-op for /mcp.
  plug ContractWeb.MCP.RawBodyReader

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug ContractWeb.Router
end
